import {
  User,
  Tournament,
  Team,
  Match,
  MatchResult,
  Dispute,
  Achievement,
  College,
  CertificateRecord,
  PushNotification,
  Registration,
  WalletTransaction,
} from '../types';

export const INITIAL_CURRENT_USER: User = {
  id: 'usr-001',
  email: 'aman.vortex@gmail.com',
  phone: '+91 98765 43210',
  username: 'vortex_rex',
  displayName: 'Aman Sharma',
  avatarUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
  bio: 'Competitive Free Fire MAX IGL & Rusher | Captain of Vortex Gaming | Aiming for National Finals 🇮🇳',
  dateOfBirth: '2003-05-14',
  role: 'TEAM_CAPTAIN',
  status: 'Active',
  teamId: 'team-001',
  collegeId: 'col-001',
  collegeCourse: 'B.Tech Computer Science',
  collegeYear: 3,
  walletBalance: 125,
  winningsBalance: 85,
  instagram: '@aman_vortex_ff',
  youtube: 'VortexGamingFF',
  discord: 'VortexRex#8821',
  createdAt: '2025-11-10T10:00:00Z',
  gamerProfile: {
    id: 'gp-001',
    userId: 'usr-001',
    gameUid: '982347101',
    gameName: 'VORTEX_REX',
    region: 'IND',
    rating: 1680,
    tier: 'Diamond',
    rank: 42,
    totalMatches: 84,
    totalTournaments: 22,
    totalWins: 18,
    top3Finishes: 38,
    top10Finishes: 64,
    totalKills: 342,
    avgKills: 4.07,
    avgPlacement: 3.2,
    winRate: 21.4,
    headshotRate: 46.8,
    verified: true,
  },
};

export const INITIAL_WALLET_TRANSACTIONS: WalletTransaction[] = [
  {
    id: 'tx-001',
    type: 'WINNING',
    title: 'Match #1 Booyah: 8 Kills (₹80) + ₹20 Bonus',
    amount: 100,
    date: 'Today, 2:15 PM',
    status: 'CREDITED',
    utrRef: 'WIN-8391047-1',
  },
  {
    id: 'tx-002',
    type: 'ENTRY',
    title: 'Entry Fee: Bermuda 48P Match #104',
    amount: -15,
    date: 'Today, 1:45 PM',
    status: 'PAID',
  },
  {
    id: 'tx-003',
    type: 'WITHDRAW',
    title: 'Instant UPI Withdrawal to aman@okaxis',
    amount: -50,
    date: 'Yesterday, 6:30 PM',
    status: 'SUCCESS',
    utrRef: 'UPI-99201948',
  },
  {
    id: 'tx-004',
    type: 'DEPOSIT',
    title: 'Added Cash via PhonePe UPI',
    amount: 100,
    date: '26 Aug 2026',
    status: 'SUCCESS',
    utrRef: 'DEP-77218390',
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-1',
    title: 'First Blood',
    description: 'Secure first kill in any tournament match',
    icon: 'Sword',
    category: 'MATCH',
    badgeTier: 'BRONZE',
    requirementCount: 1,
    unlockedAt: '2026-01-15T12:00:00Z',
  },
  {
    id: 'ach-2',
    title: 'Booyah Master',
    description: 'Win 10 Battle Royale tournament matches',
    icon: 'Trophy',
    category: 'MATCH',
    badgeTier: 'GOLD',
    requirementCount: 10,
    unlockedAt: '2026-02-10T18:30:00Z',
  },
  {
    id: 'ach-3',
    title: 'Top Fragger',
    description: 'Achieve highest kill count in a tournament',
    icon: 'Flame',
    category: 'KILL',
    badgeTier: 'SILVER',
    requirementCount: 1,
    unlockedAt: '2026-02-18T16:00:00Z',
  },
  {
    id: 'ach-4',
    title: 'Sharpshooter',
    description: 'Score 10 or more kills in a single match',
    icon: 'Crosshair',
    category: 'KILL',
    badgeTier: 'PLATINUM',
    requirementCount: 10,
    unlockedAt: '2026-02-22T19:40:00Z',
  },
  {
    id: 'ach-5',
    title: 'Diamond Challenger',
    description: 'Reach 1600+ MMR Rating on National Leaderboard',
    icon: 'Award',
    category: 'RATING',
    badgeTier: 'DIAMOND',
    requirementCount: 1600,
    unlockedAt: '2026-02-25T14:20:00Z',
  },
];

export const INITIAL_COLLEGES: College[] = [
  {
    id: 'col-001',
    name: 'Indian Institute of Technology Bombay',
    shortCode: 'IIT Bombay',
    logoUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&auto=format&fit=crop&q=80',
    city: 'Mumbai',
    state: 'Maharashtra',
    isVerified: true,
    totalPoints: 4280,
    leaderboardRank: 1,
    studentCount: 380,
    activeTeamsCount: 6,
  },
  {
    id: 'col-002',
    name: 'Delhi Technological University',
    shortCode: 'DTU Delhi',
    logoUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=120&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&auto=format&fit=crop&q=80',
    city: 'New Delhi',
    state: 'Delhi',
    isVerified: true,
    totalPoints: 3850,
    leaderboardRank: 2,
    studentCount: 290,
    activeTeamsCount: 5,
  },
  {
    id: 'col-003',
    name: 'National Institute of Technology Trichy',
    shortCode: 'NIT Trichy',
    logoUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=120&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=600&auto=format&fit=crop&q=80',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    isVerified: true,
    totalPoints: 3420,
    leaderboardRank: 3,
    studentCount: 240,
    activeTeamsCount: 4,
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-001',
    name: 'Vortex Gaming',
    tag: 'VRX',
    logoUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=120&auto=format&fit=crop&q=80',
    captainId: 'usr-001',
    captainName: 'Aman Sharma',
    rating: 1720,
    tier: 'Diamond',
    wins: 24,
    matchesPlayed: 56,
    inviteCode: 'VRX-8891',
    collegeId: 'col-001',
    collegeName: 'Indian Institute of Technology Bombay',
    createdAt: '2025-11-15T00:00:00Z',
    members: [
      {
        id: 'tm-001',
        teamId: 'team-001',
        userId: 'usr-001',
        role: 'CAPTAIN',
        status: 'CONFIRMED',
        joinedAt: '2025-11-15T00:00:00Z',
        user: {
          displayName: 'Aman Sharma',
          username: 'vortex_rex',
          avatarUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
          gamerProfile: {
            gameUid: '982347101',
            gameName: 'VORTEX_REX',
            tier: 'Diamond',
            rating: 1680,
          },
        },
      },
      {
        id: 'tm-002',
        teamId: 'team-001',
        userId: 'usr-002',
        role: 'MEMBER',
        status: 'CONFIRMED',
        joinedAt: '2025-11-16T00:00:00Z',
        user: {
          displayName: 'Rohan Mehra',
          username: 'shadow_sniper',
          avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
          gamerProfile: {
            gameUid: '883920194',
            gameName: 'SHADOW_SNIPER',
            tier: 'Platinum',
            rating: 1520,
          },
        },
      },
    ],
  },
  {
    id: 'team-002',
    name: 'Hyderabad Phoenix',
    tag: 'HYD',
    logoUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=120&auto=format&fit=crop&q=80',
    captainId: 'usr-005',
    captainName: 'Kabir Patel',
    rating: 1980,
    tier: 'Grandmaster',
    wins: 38,
    matchesPlayed: 80,
    inviteCode: 'HYD-5512',
    createdAt: '2025-10-01T00:00:00Z',
    members: [],
  },
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'match-001',
    tournamentId: 'tour-001',
    matchNumber: 1,
    title: 'Round 1 - Bermuda Battle Royale (48 Slots)',
    map: 'Bermuda',
    roomId: '8391047',
    roomPassword: 'arenaff2026',
    roomReleaseTime: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
    status: 'ROOM_READY',
    isRoomReleased: true,
  },
  {
    id: 'match-002',
    tournamentId: 'tour-002',
    matchNumber: 1,
    title: 'Kalahari Solo Cash Rush (48 Slots)',
    map: 'Kalahari',
    roomId: '9182374',
    roomPassword: 'booyah99',
    roomReleaseTime: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 10 * 60 * 1000).toISOString(),
    status: 'ROOM_READY',
    isRoomReleased: true,
  },
];

export const INITIAL_TOURNAMENTS: Tournament[] = [
  {
    id: 'tour-001',
    organizerId: 'admin-001',
    organizerName: 'Official FF Arena Admin',
    organizerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    organizerVerified: true,
    name: 'Free Fire India Champions Trophy 2026',
    slug: 'ff-india-champions-trophy-2026',
    description: 'Official Admin 48-player battle royale match with ₹15 entry fee and ₹10 per kill cash reward. +₹20 Booyah extra bonus, +₹15 for 2nd & 3rd place.',
    game: 'Free Fire MAX',
    gameVersion: 'OB48 Latest',
    mode: 'Battle Royale',
    matchMode: 'SOLO',
    format: 'Solo (48 Slots)',
    teamSize: 1,
    map: 'Bermuda',
    entryFee: 15,
    perKillReward: 10,
    prizePool: 530,
    prizes: [
      { rank: '🥇 1st Place (Booyah)', prize: '₹10 / Kill + ₹20 Extra' },
      { rank: '🥈 2nd Place', prize: '₹10 / Kill + ₹15 Extra' },
      { rank: '🥉 3rd Place', prize: '₹10 / Kill + ₹15 Extra' },
      { rank: '🔥 4th - 48th Placements', prize: '₹10 / Kill (No extra)' },
    ],
    maxParticipants: 48,
    currentParticipants: 47,
    registrationDeadline: new Date(Date.now() + 5 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
    status: 'Registration Open',
    rules: [
      'Published by Official Admin. Regular users participate by booking slots.',
      '₹15 entry fee per slot. 48 slots total.',
      'Custom room ID & password unlock automatically when all 48 players join.',
      'Per-kill prize: ₹10 per kill confirmed by AI screenshot OCR.',
      'Placement Bonus: 1st Place +₹20 extra, 2nd & 3rd Place +₹15 extra (No extra for 4th-48th).',
      'Winnings credited directly to wallet for instant UPI withdrawal.',
      'Mobile devices only. Emulators strictly prohibited.',
    ],
    scoringSystem: {
      placementPoints: { 1: 12, 2: 9, 3: 8, 4: 7, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoint: 1,
    },
    rewardDescription: '🏆 ₹10 / Kill + ₹20 Booyah Bonus + ₹15 (2nd & 3rd)',
    bannerUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    matches: INITIAL_MATCHES,
  },
  {
    id: 'tour-002',
    organizerId: 'admin-001',
    organizerName: 'Official FF Arena Admin',
    organizerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    organizerVerified: true,
    name: 'Kalahari 48-Player Cash Rush',
    slug: 'kalahari-cash-rush-48',
    description: 'Official Admin 48-player desert clash. ₹15 entry fee, ₹10/kill + ₹20 Booyah bonus.',
    game: 'Free Fire MAX',
    gameVersion: 'Latest',
    mode: 'Battle Royale',
    matchMode: 'SOLO',
    format: '48-Player Solo Battle Royale',
    teamSize: 1,
    map: 'Kalahari',
    entryFee: 15,
    perKillReward: 10,
    prizePool: 530,
    prizes: [
      { rank: '🥇 1st Place (Booyah)', prize: '₹10 / Kill + ₹20 Extra' },
      { rank: '🥈 2nd Place', prize: '₹10 / Kill + ₹15 Extra' },
      { rank: '🥉 3rd Place', prize: '₹10 / Kill + ₹15 Extra' },
      { rank: '🔥 4th - 48th Placements', prize: '₹10 / Kill' },
    ],
    maxParticipants: 48,
    currentParticipants: 48,
    registrationDeadline: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 10 * 60 * 1000).toISOString(),
    status: 'Live',
    rules: [
      'Published by Official Admin.',
      '₹15 entry fee per slot. 48 slots total.',
      '₹10/kill bounty + ₹20 extra for 1st place, ₹15 extra for 2nd & 3rd place.',
      'Winnings credited directly to wallet for instant UPI withdrawal.',
    ],
    scoringSystem: {
      placementPoints: { 1: 12, 2: 9, 3: 8, 4: 7, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoint: 1,
    },
    rewardDescription: '🏆 ₹10 / Kill + ₹20 Booyah Bonus + ₹15 (2nd/3rd)',
    bannerUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80',
    matches: [INITIAL_MATCHES[1]],
  },
  {
    id: 'tour-003',
    organizerId: 'admin-001',
    organizerName: 'Official FF Arena Admin',
    organizerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    organizerVerified: true,
    name: 'All-India Inter-College Grand Slam',
    slug: 'all-india-inter-college-grand-slam',
    description: 'Premier collegiate esports league. Compete representing your university with ₹15 entry in 48-slot lobbies.',
    game: 'Free Fire MAX',
    gameVersion: 'OB48 Latest',
    mode: 'College',
    matchMode: 'SQUAD',
    format: 'Squad (12 Teams × 4 Players = 48 Slots)',
    teamSize: 4,
    map: 'Purgatory',
    entryFee: 15,
    perKillReward: 10,
    prizePool: 530,
    prizes: [
      { rank: '🥇 1st Place (Booyah)', prize: '₹10 / Kill + ₹20 Extra' },
      { rank: '🥈 2nd Place', prize: '₹10 / Kill + ₹15 Extra' },
      { rank: '🥉 3rd Place', prize: '₹10 / Kill + ₹15 Extra' },
    ],
    maxParticipants: 48,
    currentParticipants: 32,
    registrationDeadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'Registration Open',
    rules: [
      'Admin verified college league.',
      'Valid College ID required for all squad members.',
      'Points accrue to College Leaderboard.',
    ],
    scoringSystem: {
      placementPoints: { 1: 15, 2: 12, 3: 10, 4: 8, 5: 6, 6: 4, 7: 2, 8: 1 },
      killPoint: 2,
    },
    rewardDescription: '🎓 Verified University Certificate + ₹10/Kill + ₹20 Bonus',
    bannerUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    sponsorName: 'RedBull Gaming India',
    isCollegeOnly: true,
  },

  // --- SOLO ---
  {
    id: 'tour-004',
    organizerId: 'admin-001',
    organizerName: 'Official FF Arena Admin',
    organizerAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100&auto=format&fit=crop&q=80',
    organizerVerified: true,
    name: 'Alpine Solo Booyah Cup',
    slug: 'alpine-solo-booyah-cup',
    description: '48 solo warriors battle it out on Alpine for cash kills and Booyah glory. ₹15 entry, ₹10/kill + ₹20 Booyah bonus.',
    game: 'Free Fire MAX',
    gameVersion: 'OB48 Latest',
    mode: 'Battle Royale',
    matchMode: 'SOLO',
    format: 'Solo (48 Players)',
    teamSize: 1,
    map: 'Alpine',
    entryFee: 15,
    perKillReward: 10,
    prizePool: 530,
    prizes: [
      { rank: '🥇 1st Place (Booyah)', prize: '₹10/Kill + ₹20 Extra' },
      { rank: '🥈 2nd Place', prize: '₹10/Kill + ₹15 Extra' },
      { rank: '🥉 3rd Place', prize: '₹10/Kill + ₹15 Extra' },
      { rank: '⚔️ 4th–48th Place', prize: '₹10/Kill Only' },
    ],
    maxParticipants: 48,
    currentParticipants: 29,
    registrationDeadline: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    status: 'Registration Open',
    rules: [
      'Admin-published solo tournament. 48 individual player slots.',
      '₹15 entry fee per player.',
      '₹10 per confirmed kill via AI OCR.',
      'Placement Bonus: 1st +₹20, 2nd +₹15, 3rd +₹15.',
      'No team formation required. You play alone.',
    ],
    scoringSystem: {
      placementPoints: { 1: 12, 2: 9, 3: 8, 4: 7, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoint: 1,
    },
    rewardDescription: '🏆 ₹10/Kill + ₹20 Booyah Bonus',
    bannerUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    matches: [],
  },

  // --- DUO ---
  {
    id: 'tour-005',
    organizerId: 'admin-001',
    organizerName: 'Official FF Arena Admin',
    organizerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    organizerVerified: true,
    name: 'Bermuda Duo Clash',
    slug: 'bermuda-duo-clash',
    description: '24 duo teams (48 players total) on Bermuda. ₹25 entry per team, ₹10/kill per player + ₹20 Booyah bonus.',
    game: 'Free Fire MAX',
    gameVersion: 'OB48 Latest',
    mode: 'Duo',
    matchMode: 'DUO',
    format: 'Duo (24 Teams × 2 Players = 48 Slots)',
    teamSize: 2,
    map: 'Bermuda',
    entryFee: 25,
    perKillReward: 10,
    prizePool: 700,
    prizes: [
      { rank: '🥇 1st Duo (Booyah)', prize: '₹10/Kill/Player + ₹20 Extra/Player' },
      { rank: '🥈 2nd Duo', prize: '₹10/Kill/Player + ₹15 Extra/Player' },
      { rank: '🥉 3rd Duo', prize: '₹10/Kill/Player + ₹15 Extra/Player' },
      { rank: '⚔️ 4th–24th Duo', prize: '₹10/Kill/Player Only' },
    ],
    maxParticipants: 48,
    currentParticipants: 18,
    registrationDeadline: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    status: 'Registration Open',
    rules: [
      'Admin-published DUO tournament. 24 duo teams. 48 total player slots.',
      '₹25 entry fee per duo team.',
      'Both players must register under the same duo team.',
      'Per-kill prize ₹10 per confirmed kill per player.',
      'Booyah Bonus: Duo champs get +₹20/player extra, 2nd/3rd Duo get +₹15/player.',
    ],
    scoringSystem: {
      placementPoints: { 1: 12, 2: 9, 3: 8, 4: 7, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoint: 1,
    },
    rewardDescription: '👥 Duo ₹10/Kill/Player + ₹20 Booyah Bonus',
    bannerUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80',
    matches: [],
  },

  // --- SQUAD ---
  {
    id: 'tour-006',
    organizerId: 'admin-001',
    organizerName: 'Official FF Arena Admin',
    organizerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    organizerVerified: true,
    name: 'Kalahari Squad Showdown',
    slug: 'kalahari-squad-showdown',
    description: '12 squads (48 players) clash for Booyah supremacy on Kalahari. ₹50/squad entry, ₹10/kill per player.',
    game: 'Free Fire MAX',
    gameVersion: 'OB48 Latest',
    mode: 'Squad',
    matchMode: 'SQUAD',
    format: 'Squad (12 Teams × 4 Players = 48 Slots)',
    teamSize: 4,
    map: 'Kalahari',
    entryFee: 50,
    perKillReward: 10,
    prizePool: 700,
    prizes: [
      { rank: '🥇 1st Squad (Booyah)', prize: '₹10/Kill/Player + ₹20 Extra/Player' },
      { rank: '🥈 2nd Squad', prize: '₹10/Kill/Player + ₹15 Extra/Player' },
      { rank: '🥉 3rd Squad', prize: '₹10/Kill/Player + ₹15 Extra/Player' },
      { rank: '⚔️ 4th–12th Squad', prize: '₹10/Kill/Player Only' },
    ],
    maxParticipants: 48,
    currentParticipants: 36,
    registrationDeadline: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    status: 'Registration Open',
    rules: [
      'Admin-published SQUAD tournament. 12 squads, 4 players each. 48 total slots.',
      '₹50 entry fee per squad (₹12.50 per player).',
      'IGL (Captain) registers team and pays entry fee.',
      'Per-kill prize ₹10 per confirmed kill per player.',
      'Booyah Bonus: Winning squad gets +₹20/player, 2nd/3rd squad get +₹15/player.',
      'Minimum 3 active members required to play. Max 4.',
    ],
    scoringSystem: {
      placementPoints: { 1: 15, 2: 12, 3: 10, 4: 8, 5: 6, 6: 4, 7: 3, 8: 2, 9: 1, 10: 0 },
      killPoint: 2,
    },
    rewardDescription: '🛡️ Squad ₹10/Kill/Player + ₹20 Booyah Bonus',
    bannerUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    matches: [],
  },
];

export const INITIAL_MATCH_RESULTS: MatchResult[] = [
  {
    id: 'res-001',
    matchId: 'match-001',
    tournamentId: 'tour-001',
    userId: 'usr-001',
    teamId: 'team-001',
    playerName: 'Aman Sharma',
    gameUid: '982347101',
    kills: 8,
    placement: 1,
    totalPoints: 20,
    rewardCashWon: 100, // 8 * 10 + 20
    screenshotUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    aiOcrData: {
      detectedIgn: 'VORTEX_REX',
      detectedKills: 8,
      detectedPlacement: 1,
      detectedDamage: 2450,
      confidenceScore: 98,
      fraudFlags: [],
      ocrTextRaw: 'BOOYAH! #1/48 - VORTEX_REX - KILLS: 8 - DAMAGE: 2450',
    },
    verificationStatus: 'Approved',
    verifiedBy: 'AI_OCR_ENGINE_V2',
    submittedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'res-002',
    matchId: 'match-001',
    tournamentId: 'tour-001',
    userId: 'usr-003',
    playerName: 'GLK_ARJUN',
    gameUid: '772391024',
    kills: 6,
    placement: 2,
    totalPoints: 15,
    rewardCashWon: 75, // 6 * 10 + 15
    screenshotUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80',
    verificationStatus: 'Approved',
    verifiedBy: 'AI_OCR_ENGINE_V2',
    submittedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'res-003',
    matchId: 'match-001',
    tournamentId: 'tour-001',
    userId: 'usr-004',
    playerName: 'HYD_KABIR',
    gameUid: '662019481',
    kills: 5,
    placement: 3,
    totalPoints: 13,
    rewardCashWon: 65, // 5 * 10 + 15
    screenshotUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    verificationStatus: 'Approved',
    verifiedBy: 'AI_OCR_ENGINE_V2',
    submittedAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_DISPUTES: Dispute[] = [
  {
    id: 'disp-001',
    resultId: 'res-002',
    matchId: 'match-001',
    tournamentId: 'tour-001',
    filedByUserId: 'usr-001',
    filedByName: 'Aman Sharma (VORTEX_REX)',
    againstUserId: 'usr-003',
    againstName: 'GLK_ARJUN',
    reasonCategory: 'WRONG_PLACEMENT',
    description: 'Player GLK_ARJUN claims #2 placement, but died at #3 during the final safe zone shrink.',
    evidenceUrls: ['https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80'],
    status: 'Open',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_CERTIFICATES: CertificateRecord[] = [
  {
    id: 'cert-001',
    certificateNumber: 'FF-2026-8X73KD',
    certificateId: 'FF-2026-8X73KD',
    tournamentId: 'tour-001',
    tournamentName: 'Free Fire India Champions Trophy 2026',
    userId: 'usr-001',
    recipientName: 'Aman Sharma',
    recipientGameUid: '982347101',
    recipientIgn: 'VORTEX_REX',
    teamName: 'Vortex Gaming',
    rankAchieved: 1,
    achievementTitle: '1st Place - Champion (Booyah)',
    killsCount: 8,
    issueDate: '2026-08-28',
    qrPayloadUrl: 'https://ffarena.gg/verify/FF-2026-8X73KD',
    organizerName: 'Official FF Arena Admin',
    digitalSignatureHash: '3a7b9c1d2e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
  },
];

export const INITIAL_NOTIFICATIONS: PushNotification[] = [
  {
    id: 'notif-001',
    userId: 'usr-001',
    title: 'Custom Room Credentials Live! 🔑',
    body: 'Room ID: 8391047 | Pass: arenaff2026. Round 1 starts in 15 mins!',
    type: 'ROOM_DETAILS',
    dataPayload: { matchId: 'match-001' },
    isRead: false,
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-002',
    userId: 'usr-001',
    title: 'Winnings Credited: ₹100 🏆',
    body: 'AI OCR verified 8 kills (₹80) + ₹20 Booyah bonus credited to your wallet.',
    type: 'WALLET_CREDIT',
    isRead: false,
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
];
