import {
  User,
  Tournament,
  Team,
  Match,
  MatchResult,
  Dispute,
  Achievement,
  College,
  CertificateRecord,
  PushNotification,
  Registration,
  WalletTransaction,
} from "../types";

export const INITIAL_CURRENT_USER: User = {
  id: "usr-default",
  email: "",
  phone: "",
  username: "player",
  displayName: "Player",
  avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
  bio: "Free Fire MAX Competitor",
  dateOfBirth: "2004-01-01",
  role: "PLAYER",
  status: "Active",
  walletBalance: 0,
  winningsBalance: 0,
  createdAt: new Date().toISOString(),
  gamerProfile: {
    id: "gp-default",
    userId: "usr-default",
    gameUid: "",
    gameName: "PLAYER",
    region: "IND",
    rating: 1000,
    tier: "Bronze",
    rank: 0,
    totalMatches: 0,
    totalTournaments: 0,
    totalWins: 0,
    top3Finishes: 0,
    top10Finishes: 0,
    totalKills: 0,
    avgKills: 0,
    avgPlacement: 0,
    winRate: 0,
    headshotRate: 0,
    verified: false,
  },
};

export const INITIAL_WALLET_TRANSACTIONS: WalletTransaction[] = [];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: "ach-1",
    title: "First Blood",
    description: "Secure first kill in any tournament match",
    icon: "Sword",
    category: "MATCH",
    badgeTier: "BRONZE",
    requirementCount: 1,
    unlockedAt: "",
  },
  {
    id: "ach-2",
    title: "Booyah Master",
    description: "Win 10 Battle Royale tournament matches",
    icon: "Trophy",
    category: "MATCH",
    badgeTier: "GOLD",
    requirementCount: 10,
    unlockedAt: "",
  },
  {
    id: "ach-3",
    title: "Top Fragger",
    description: "Achieve highest kill count in a tournament",
    icon: "Flame",
    category: "KILL",
    badgeTier: "SILVER",
    requirementCount: 1,
    unlockedAt: "",
  },
  {
    id: "ach-4",
    title: "Sharpshooter",
    description: "Score 10 or more kills in a single match",
    icon: "Crosshair",
    category: "KILL",
    badgeTier: "PLATINUM",
    requirementCount: 10,
    unlockedAt: "",
  },
  {
    id: "ach-5",
    title: "Diamond Challenger",
    description: "Reach 1600+ MMR Rating on National Leaderboard",
    icon: "Award",
    category: "RATING",
    badgeTier: "DIAMOND",
    requirementCount: 1600,
    unlockedAt: "",
  },
];

export const INITIAL_COLLEGES: College[] = [
  {
    id: "col-001",
    name: "Indian Institute of Technology Bombay",
    shortCode: "IIT Bombay",
    logoUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&auto=format&fit=crop&q=80",
    city: "Mumbai",
    state: "Maharashtra",
    isVerified: true,
    totalPoints: 0,
    leaderboardRank: 1,
    studentCount: 0,
    activeTeamsCount: 0,
  },
  {
    id: "col-002",
    name: "Delhi Technological University",
    shortCode: "DTU Delhi",
    logoUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=120&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&auto=format&fit=crop&q=80",
    city: "New Delhi",
    state: "Delhi",
    isVerified: true,
    totalPoints: 0,
    leaderboardRank: 2,
    studentCount: 0,
    activeTeamsCount: 0,
  },
  {
    id: "col-003",
    name: "National Institute of Technology Trichy",
    shortCode: "NIT Trichy",
    logoUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=120&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=600&auto=format&fit=crop&q=80",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    isVerified: true,
    totalPoints: 0,
    leaderboardRank: 3,
    studentCount: 0,
    activeTeamsCount: 0,
  },
];

export const INITIAL_TEAMS: Team[] = [];

export const INITIAL_MATCHES: Match[] = [
  {
    id: "match-001",
    tournamentId: "tour-001",
    matchNumber: 1,
    title: "Round 1 - Bermuda Battle Royale (48 Slots)",
    map: "Bermuda",
    roomId: "8391047",
    roomPassword: "arenaff2026",
    roomReleaseTime: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 90 * 60 * 1000).toISOString(),
    status: "UPCOMING",
    isRoomReleased: false,
  },
  {
    id: "match-002",
    tournamentId: "tour-002",
    matchNumber: 1,
    title: "Kalahari Solo Cash Rush (48 Slots)",
    map: "Kalahari",
    roomId: "9182374",
    roomPassword: "booyah99",
    roomReleaseTime: new Date(Date.now() + 120 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 150 * 60 * 1000).toISOString(),
    status: "UPCOMING",
    isRoomReleased: false,
  },
];

export const INITIAL_TOURNAMENTS: Tournament[] = [
  {
    id: "tour-001",
    organizerId: "admin-001",
    organizerName: "Official FF Arena Admin",
    organizerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    organizerVerified: true,
    name: "Free Fire India Champions Trophy 2026",
    slug: "ff-india-champions-trophy-2026",
    description: "Official Admin 48-player battle royale match with ₹15 entry fee and ₹10 per kill cash reward. +₹20 Booyah extra bonus, +₹15 for 2nd & 3rd place.",
    game: "Free Fire MAX",
    gameVersion: "OB48 Latest",
    mode: "Battle Royale",
    matchMode: "SOLO",
    format: "Solo (48 Slots)",
    teamSize: 1,
    map: "Bermuda",
    entryFee: 15,
    perKillReward: 10,
    prizePool: 530,
    prizes: [
      { rank: "🥇 1st Place (Booyah)", prize: "₹10 / Kill + ₹20 Extra" },
      { rank: "🥈 2nd Place", prize: "₹10 / Kill + ₹15 Extra" },
      { rank: "🥉 3rd Place", prize: "₹10 / Kill + ₹15 Extra" },
      { rank: "🔥 4th - 48th Placements", prize: "₹10 / Kill (No extra)" },
    ],
    maxParticipants: 48,
    currentParticipants: 0,
    registrationDeadline: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    status: "Registration Open",
    rules: [
      "Published by Official Admin. Regular users participate by booking slots.",
      "₹15 entry fee per slot. 48 slots total.",
      "Custom room ID & password unlock automatically when all 48 players join.",
      "Per-kill prize: ₹10 per kill confirmed by AI screenshot OCR.",
      "Placement Bonus: 1st Place +₹20 extra, 2nd & 3rd Place +₹15 extra (No extra for 4th-48th).",
      "Winnings credited directly to wallet for instant UPI withdrawal.",
      "Mobile devices only. Emulators strictly prohibited.",
    ],
    scoringSystem: {
      placementPoints: { 1: 12, 2: 9, 3: 8, 4: 7, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoint: 1,
    },
    rewardDescription: "🏆 ₹10 / Kill + ₹20 Booyah Bonus + ₹15 (2nd & 3rd)",
    bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80",
    matches: [INITIAL_MATCHES[0]],
  },
  {
    id: "tour-002",
    organizerId: "admin-001",
    organizerName: "Official FF Arena Admin",
    organizerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    organizerVerified: true,
    name: "Kalahari 48-Player Cash Rush",
    slug: "kalahari-cash-rush-48",
    description: "Official Admin 48-player desert clash. ₹15 entry fee, ₹10/kill + ₹20 Booyah bonus.",
    game: "Free Fire MAX",
    gameVersion: "Latest",
    mode: "Battle Royale",
    matchMode: "SOLO",
    format: "48-Player Solo Battle Royale",
    teamSize: 1,
    map: "Kalahari",
    entryFee: 15,
    perKillReward: 10,
    prizePool: 530,
    prizes: [
      { rank: "🥇 1st Place (Booyah)", prize: "₹10 / Kill + ₹20 Extra" },
      { rank: "🥈 2nd Place", prize: "₹10 / Kill + ₹15 Extra" },
      { rank: "🥉 3rd Place", prize: "₹10 / Kill + ₹15 Extra" },
      { rank: "🔥 4th - 48th Placements", prize: "₹10 / Kill" },
    ],
    maxParticipants: 48,
    currentParticipants: 0,
    registrationDeadline: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    status: "Registration Open",
    rules: [
      "Published by Official Admin.",
      "₹15 entry fee per slot. 48 slots total.",
      "₹10/kill bounty + ₹20 extra for 1st place, ₹15 extra for 2nd & 3rd place.",
      "Winnings credited directly to wallet for instant UPI withdrawal.",
    ],
    scoringSystem: {
      placementPoints: { 1: 12, 2: 9, 3: 8, 4: 7, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoint: 1,
    },
    rewardDescription: "🏆 ₹10 / Kill + ₹20 Booyah Bonus + ₹15 (2nd/3rd)",
    bannerUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80",
    matches: [INITIAL_MATCHES[1]],
  },
  {
    id: "tour-003",
    organizerId: "admin-001",
    organizerName: "Official FF Arena Admin",
    organizerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    organizerVerified: true,
    name: "All-India Inter-College Grand Slam",
    slug: "all-india-inter-college-grand-slam",
    description: "Premier collegiate esports league. Compete representing your university with ₹15 entry in 48-slot lobbies.",
    game: "Free Fire MAX",
    gameVersion: "OB48 Latest",
    mode: "College",
    matchMode: "SQUAD",
    format: "Squad (12 Teams × 4 Players = 48 Slots)",
    teamSize: 4,
    map: "Purgatory",
    entryFee: 15,
    perKillReward: 10,
    prizePool: 530,
    prizes: [
      { rank: "🥇 1st Place (Booyah)", prize: "₹10 / Kill + ₹20 Extra" },
      { rank: "🥈 2nd Place", prize: "₹10 / Kill + ₹15 Extra" },
      { rank: "🥉 3rd Place", prize: "₹10 / Kill + ₹15 Extra" },
    ],
    maxParticipants: 48,
    currentParticipants: 0,
    registrationDeadline: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    status: "Registration Open",
    rules: [
      "Admin verified college league.",
      "Valid College ID required for all squad members.",
      "Points accrue to College Leaderboard.",
    ],
    scoringSystem: {
      placementPoints: { 1: 15, 2: 12, 3: 10, 4: 8, 5: 6, 6: 4, 7: 2, 8: 1 },
      killPoint: 2,
    },
    rewardDescription: "🎓 Verified University Certificate + ₹10/Kill + ₹20 Bonus",
    bannerUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80",
    sponsorName: "RedBull Gaming India",
    isCollegeOnly: true,
  },
  {
    id: "tour-004",
    organizerId: "admin-001",
    organizerName: "Official FF Arena Admin",
    organizerAvatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100&auto=format&fit=crop&q=80",
    organizerVerified: true,
    name: "Alpine Solo Booyah Cup",
    slug: "alpine-solo-booyah-cup",
    description: "48 solo warriors battle it out on Alpine for cash kills and Booyah glory. ₹15 entry, ₹10/kill + ₹20 Booyah bonus.",
    game: "Free Fire MAX",
    gameVersion: "OB48 Latest",
    mode: "Battle Royale",
    matchMode: "SOLO",
    format: "Solo (48 Players)",
    teamSize: 1,
    map: "Alpine",
    entryFee: 15,
    perKillReward: 10,
    prizePool: 530,
    prizes: [
      { rank: "🥇 1st Place (Booyah)", prize: "₹10/Kill + ₹20 Extra" },
      { rank: "🥈 2nd Place", prize: "₹10/Kill + ₹15 Extra" },
      { rank: "🥉 3rd Place", prize: "₹10/Kill + ₹15 Extra" },
      { rank: "⚔️ 4th–48th Place", prize: "₹10/Kill Only" },
    ],
    maxParticipants: 48,
    currentParticipants: 0,
    registrationDeadline: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 7 * 60 * 60 * 1000).toISOString(),
    status: "Registration Open",
    rules: [
      "Admin-published solo tournament. 48 individual player slots.",
      "₹15 entry fee per player.",
      "₹10 per confirmed kill via AI OCR.",
      "Placement Bonus: 1st +₹20, 2nd +₹15, 3rd +₹15.",
      "No team formation required. You play alone.",
    ],
    scoringSystem: {
      placementPoints: { 1: 12, 2: 9, 3: 8, 4: 7, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoint: 1,
    },
    rewardDescription: "🏆 ₹10/Kill + ₹20 Booyah Bonus",
    bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80",
    matches: [],
  },
  {
    id: "tour-005",
    organizerId: "admin-001",
    organizerName: "Official FF Arena Admin",
    organizerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    organizerVerified: true,
    name: "Bermuda Duo Clash",
    slug: "bermuda-duo-clash",
    description: "24 duo teams (48 players total) on Bermuda. ₹25 entry per team, ₹10/kill per player + ₹20 Booyah bonus.",
    game: "Free Fire MAX",
    gameVersion: "OB48 Latest",
    mode: "Duo",
    matchMode: "DUO",
    format: "Duo (24 Teams × 2 Players = 48 Slots)",
    teamSize: 2,
    map: "Bermuda",
    entryFee: 25,
    perKillReward: 10,
    prizePool: 700,
    prizes: [
      { rank: "🥇 1st Duo (Booyah)", prize: "₹10/Kill/Player + ₹20 Extra/Player" },
      { rank: "🥈 2nd Duo", prize: "₹10/Kill/Player + ₹15 Extra/Player" },
      { rank: "🥉 3rd Duo", prize: "₹10/Kill/Player + ₹15 Extra/Player" },
      { rank: "⚔️ 4th–24th Duo", prize: "₹10/Kill/Player Only" },
    ],
    maxParticipants: 48,
    currentParticipants: 0,
    registrationDeadline: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString(),
    status: "Registration Open",
    rules: [
      "Admin-published DUO tournament. 24 duo teams. 48 total player slots.",
      "₹25 entry fee per duo team.",
      "Both players must register under the same duo team.",
      "Per-kill prize ₹10 per confirmed kill per player.",
      "Booyah Bonus: Duo champs get +₹20/player extra, 2nd/3rd Duo get +₹15/player.",
    ],
    scoringSystem: {
      placementPoints: { 1: 12, 2: 9, 3: 8, 4: 7, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1 },
      killPoint: 1,
    },
    rewardDescription: "👥 Duo ₹10/Kill/Player + ₹20 Booyah Bonus",
    bannerUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80",
    matches: [],
  },
  {
    id: "tour-006",
    organizerId: "admin-001",
    organizerName: "Official FF Arena Admin",
    organizerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    organizerVerified: true,
    name: "Kalahari Squad Showdown",
    slug: "kalahari-squad-showdown",
    description: "12 squads (48 players) clash for Booyah supremacy on Kalahari. ₹50/squad entry, ₹10/kill per player.",
    game: "Free Fire MAX",
    gameVersion: "OB48 Latest",
    mode: "Squad",
    matchMode: "SQUAD",
    format: "Squad (12 Teams × 4 Players = 48 Slots)",
    teamSize: 4,
    map: "Kalahari",
    entryFee: 50,
    perKillReward: 10,
    prizePool: 700,
    prizes: [
      { rank: "🥇 1st Squad (Booyah)", prize: "₹10/Kill/Player + ₹20 Extra/Player" },
      { rank: "🥈 2nd Squad", prize: "₹10/Kill/Player + ₹15 Extra/Player" },
      { rank: "🥉 3rd Squad", prize: "₹10/Kill/Player + ₹15 Extra/Player" },
      { rank: "⚔️ 4th–12th Squad", prize: "₹10/Kill/Player Only" },
    ],
    maxParticipants: 48,
    currentParticipants: 0,
    registrationDeadline: new Date(Date.now() + 10 * 60 * 60 * 1000).toISOString(),
    startTime: new Date(Date.now() + 11 * 60 * 60 * 1000).toISOString(),
    status: "Registration Open",
    rules: [
      "Admin-published SQUAD tournament. 12 squads, 4 players each. 48 total slots.",
      "₹50 entry fee per squad (₹12.50 per player).",
      "IGL (Captain) registers team and pays entry fee.",
      "Per-kill prize ₹10 per confirmed kill per player.",
      "Booyah Bonus: Winning squad gets +₹20/player, 2nd/3rd squad get +₹15/player.",
      "Minimum 3 active members required to play. Max 4.",
    ],
    scoringSystem: {
      placementPoints: { 1: 15, 2: 12, 3: 10, 4: 8, 5: 6, 6: 4, 7: 3, 8: 2, 9: 1, 10: 0 },
      killPoint: 2,
    },
    rewardDescription: "🛡️ Squad ₹10/Kill/Player + ₹20 Booyah Bonus",
    bannerUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80",
    matches: [],
  },
];

export const INITIAL_MATCH_RESULTS: MatchResult[] = [];
export const INITIAL_DISPUTES: Dispute[] = [];
export const INITIAL_CERTIFICATES: CertificateRecord[] = [];
export const INITIAL_NOTIFICATIONS: PushNotification[] = [];
